keys:
  - &larstop2 age1xu8xmg3g7p0rcy769q4c4z0gymxgsmngs0n3fg6y089ms626qsrsd0n6q6
  - &ister age17msmvadf3z6sql2fh6pnd0h7gkchaupkk2zhncra47hat5pfg3nqwwnfhw


creation_rules:
  - path_regex: ^secrets.yaml$|^ister.local/.*$
    key_groups:
    - age:
      - *larstop2
      - *ister
